-- ============================================================================
-- Arena OS — 0030: payment idempotency, and refund reconciliation tracking
--
-- Two defects this closes.
--
-- 1. A DOUBLE-CLICKED TENDER TOOK THE MONEY TWICE.
--    `recordPaymentForInvoice` had no way to recognise a retry: two identical
--    submissions on an ₹800 bill both passed the overpayment check (₹400 +
--    ₹400 ≤ ₹800) and both inserted. The invoice lock made them safe against
--    OVERPAYMENT but not against DUPLICATION. An idempotency key, unique per
--    tenant, lets the second call recognise itself and return the first
--    result instead of taking the money again.
--
-- 2. A REFUND DID NOT UNDO WHAT THE PAYMENT CAUSED.
--    Refunding a bill left the loyalty points earned on it intact; refunding a
--    wallet TOP-UP returned the cash and left the credit, duplicating the
--    money outright. Reconciliation needs to be cumulative and idempotent
--    across many partial refunds, so the invoice tracks how much has already
--    been undone.
-- ============================================================================

-- ── 1. idempotency ───────────────────────────────────────────────────────────
-- Nullable: existing rows have none, and the gateway paths are already
-- idempotent through payments.gateway_payment_id (0025). Only the paths a
-- human can double-submit supply one.
alter table public.payments
  add column if not exists idempotency_key text;

-- Tenant-scoped, because the key is generated by that tenant's browser and two
-- tenants must never be able to collide with each other.
create unique index if not exists idx_payments_idempotency
  on public.payments(tenant_id, idempotency_key)
  where idempotency_key is not null;

-- ── 2. reconciliation counters ───────────────────────────────────────────────
-- Cumulative "how much of this invoice's side effects have been undone".
--
-- Counters rather than summing the ledger, because each reversal entry is keyed
-- to the REFUND that caused it (source_id = refund id, so many partial refunds
-- can each write one), which leaves no way to total them per invoice. Tracking
-- the running total here makes reconciliation idempotent and self-correcting: a
-- reversal writes only the DELTA between what should be undone and what already
-- has been, so a re-run writes nothing and a later refund tops it up.
--
-- Integer points, so flooring is done ONCE against the cumulative target rather
-- than per refund — three refunds of a third each must reverse 10 points, not
-- floor(10/3)×3 = 9.
alter table public.invoices
  add column if not exists loyalty_points_reversed integer not null default 0,
  add column if not exists wallet_credit_reversed numeric(10,2) not null default 0;

do $$ begin
  alter table public.invoices
    add constraint invoices_reversal_nonneg
    check (loyalty_points_reversed >= 0 and wallet_credit_reversed >= 0);
exception when duplicate_object then null; end $$;

-- Never undo more than was done.
do $$ begin
  alter table public.invoices
    add constraint invoices_loyalty_reversal_within_earned
    check (loyalty_points_reversed <= loyalty_points_earned);
exception when duplicate_object then null; end $$;

-- Ledger `source_type` values added here:
--   'topup_reversal'  debit  — wallet credit taken back when a top-up is
--                              refunded. source_id = the refund.
--   'earn_reversal'   debit  — loyalty points taken back when a bill is
--                              refunded or voided. source_id = refund, or the
--                              invoice when a void reconciles the remainder.
