'use server'

import { headers } from 'next/headers'
import { eq } from 'drizzle-orm'
import { z } from 'zod'
import { ownerDb } from '@/db'
import { tenants } from '@/db/schema'
import { listPublicPlans, type PublicPlan } from '@/lib/platform/plans/public'
import { normalizeSlug, slugProblem, slugProblemMessage } from '@/lib/platform/slug'
import { selfServeSignup, SignupError } from '@/lib/signup/service'
import { rateLimit } from '@/lib/security/rate-limit'
import { ipFromHeaders } from '@/lib/security/ip'
import { publicTenantUrl } from '@/lib/tenant/subdomain'
import { zodErrorMessage } from '@/lib/utils/errors'

/**
 * Public self-serve signup (M16 #6).
 *
 * These are the ONLY two server actions reachable with no session of any kind
 * that can cause a tenant to exist, so everything about them is written on the
 * assumption that the caller is hostile.
 *
 * ══ WHAT THE BROWSER MAY SEND ══════════════════════════════════════════════
 *
 *   business name · slug · industry · owner name/email/password ·
 *   plan id · 'monthly' | 'annual' · 'trial' | 'paid'
 *
 * ══ AND WHAT IT MAY NOT ════════════════════════════════════════════════════
 *
 * Every one of these is decided by the SERVER and has no field to send:
 *
 *   tenant_id            generated by the provisioning transaction
 *   owner role           hard-coded 'owner' in provisionTenant(); the function
 *                        takes no role parameter, so there is nothing to forge
 *   tenant status        'trial' — nobody has paid at signup, in either flow
 *   subscription status  'trialing'; only the verified webhook promotes it
 *   price / amount       re-read from `plans`; the amount is never even sent to
 *                        Razorpay, because a Razorpay plan carries its own
 *   entitlements         rows on the plan, never client input
 *   gateway credentials  platform_payment_settings, decrypted server-side and
 *                        never returned
 *
 * The one outward value is `checkoutUrl` — Razorpay's own hosted page, a public
 * URL the payer is meant to open. Currency and timezone are likewise NOT taken
 * from the browser: they are fixed to the platform defaults below, matching
 * what createCompany() defaults to, and an operator changes them afterwards.
 */

type SlugCheck = { available?: boolean; error?: string }

const RATE_LIMIT_MESSAGE = 'Too many attempts. Please wait a moment and try again.'

async function callerIp(): Promise<string> {
  return ipFromHeaders(await headers())
}

// ── slug availability ────────────────────────────────────────────────────────

/**
 * "Is this address free?" — for the signup form's inline feedback.
 *
 * ── This is a courtesy, not a guarantee ─────────────────────────────────────
 *
 * A `true` here does not reserve anything. Between this call and the INSERT
 * that follows, another signup can take the same slug, and the thing that
 * actually settles it is the UNIQUE constraint on `tenants.slug` — which
 * lib/signup/service.ts translates into a field error rather than a 500. That
 * is by design; see the note at the top of lib/platform/slug.ts.
 *
 * ── Enumeration ─────────────────────────────────────────────────────────────
 *
 * This endpoint answers a yes/no question about whether a business exists at a
 * given address. That is not secret — the address is a public hostname, and
 * anyone can simply visit it — but answering it thousands of times a minute
 * would hand over a tidy customer list, so it is capped per IP well below the
 * rate at which a person types. The refusal is generic and does NOT say whether
 * the slug was free, so a rate-limited attacker learns nothing.
 */
export async function checkSlugAvailability(raw: unknown): Promise<SlugCheck> {
  const ip = await callerIp()
  // 30 in 10 minutes: generous for someone trying a few names, useless for
  // walking a dictionary.
  if (!rateLimit(`signup:slug:${ip}`, 30, 10 * 60_000).ok) {
    return { error: RATE_LIMIT_MESSAGE }
  }

  const parsed = z.object({ slug: z.string().max(80) }).safeParse(raw)
  if (!parsed.success) return { error: 'Enter a workspace address.' }

  const slug = normalizeSlug(parsed.data.slug)
  const problem = slugProblem(slug)
  if (problem) return { error: slugProblemMessage(problem) }

  // Owner connection: `tenants` has no public SELECT policy, and adding one so
  // that a stranger could list workspaces would be a far larger hole than this
  // single keyed existence check. Exactly one column is read, and only a
  // boolean leaves this function.
  const [taken] = await ownerDb
    .select({ id: tenants.id })
    .from(tenants)
    .where(eq(tenants.slug, slug))
    .limit(1)

  return { available: !taken }
}

// ── the catalogue ────────────────────────────────────────────────────────────

/**
 * Active plans for the signup page's plan picker.
 *
 * A thin pass-through to the RLS-scoped reader. Rate-limited like everything
 * else public here, though the catalogue is a price list rather than a secret —
 * the cap is about the database round trip, not confidentiality.
 */
export async function loadSignupPlans(): Promise<{ plans?: PublicPlan[]; error?: string }> {
  const ip = await callerIp()
  if (!rateLimit(`signup:plans:${ip}`, 60, 10 * 60_000).ok) {
    return { error: RATE_LIMIT_MESSAGE }
  }
  try {
    return { plans: await listPublicPlans() }
  } catch (e) {
    console.error('[signup] plan catalogue read failed:', e)
    return { error: 'Could not load plans right now. Please try again.' }
  }
}

// ── signup ───────────────────────────────────────────────────────────────────

/**
 * Currency and timezone are NOT signup fields.
 *
 * createCompany() defaults them to exactly these, and every price in the
 * platform catalogue is INR (the `currency` CHECK on `plans` is a 3-char code
 * and the seed data is INR throughout). Letting a signup form pick a currency
 * would let a business register expecting to be billed in one currency while
 * Razorpay charges another. An operator changes both afterwards from the
 * company detail page.
 */
const DEFAULT_CURRENCY = 'INR'
const DEFAULT_TIMEZONE = 'Asia/Kolkata'

const signupInput = z.object({
  companyName: z.string().trim().min(1, 'Enter your business name.').max(120),
  slug: z.string().trim().min(1, 'Choose a workspace address.').max(80),
  industry: z.enum([
    'gaming_cafe',
    'recording_studio',
    'podcast_studio',
    'dance_studio',
    'vr_centre',
    'restaurant',
    'other',
  ]),
  ownerName: z.string().trim().min(1, 'Enter your name.').max(120),
  ownerEmail: z.string().trim().toLowerCase().email('Enter a valid email address.').max(255),
  // Same floor as createCompany() and addCompanyMember(), so a self-registered
  // owner is held to exactly the password rule an admin-created one is.
  ownerPassword: z.string().min(8, 'Use at least 8 characters.').max(200),
  planId: z.string().uuid('Choose a plan.'),
  billingPeriod: z.enum(['monthly', 'annual']),
  intent: z.enum(['trial', 'paid']),
})

export type SignupActionResult = {
  ok?: true
  error?: string
  /** Which field the error belongs to, when it belongs to one. */
  field?: 'slug' | 'ownerEmail' | 'planId' | null
  /** Where the owner signs in — their own subdomain. */
  loginUrl?: string
  /** Razorpay's hosted authorisation page, for a paid signup. */
  checkoutUrl?: string
  /** Set when the workspace exists but billing could not be set up. */
  planWarning?: string
}

/**
 * Create a workspace.
 *
 * ── Why the owner is NOT signed in here ─────────────────────────────────────
 *
 * Signup runs on the ROOT domain and the workspace lives on
 * `{slug}.{rootDomain}`. The session cookie set by createSession()
 * (lib/auth/session.ts) has no `domain` attribute, so it is host-only and a
 * cookie minted here would simply not be sent to the subdomain. Widening it to
 * a wildcard domain would change how EVERY existing session is scoped —
 * including the platform admin's — which is not a change this ticket should
 * make on the side.
 *
 * So signup returns the tenant's own login URL and the owner signs in there
 * with the password they just chose, through the existing staff login. That
 * reuses the authentication system exactly as it is, and has the incidental
 * property that the password is proven to work before they rely on it.
 */
export async function submitSignup(raw: unknown): Promise<SignupActionResult> {
  const ip = await callerIp()
  // Deliberately tight. Every successful call creates a tenant, a user and a
  // subscription row; this is the most expensive public endpoint in the app.
  if (!rateLimit(`signup:submit:${ip}`, 5, 60 * 60_000).ok) {
    return { error: RATE_LIMIT_MESSAGE }
  }

  const parsed = signupInput.safeParse(raw)
  if (!parsed.success) {
    return { error: zodErrorMessage(parsed.error) }
  }
  const v = parsed.data
  const slug = normalizeSlug(v.slug)

  // A second, per-email cap on top of the per-IP one: one address signing up
  // repeatedly from different IPs is the shape of automated abuse, and it is
  // also the shape of a confused person clicking twice — both are better served
  // by being told to wait.
  if (!rateLimit(`signup:email:${v.ownerEmail}`, 3, 60 * 60_000).ok) {
    return { error: RATE_LIMIT_MESSAGE }
  }

  try {
    const result = await selfServeSignup({
      companyName: v.companyName,
      slug,
      industry: v.industry,
      currency: DEFAULT_CURRENCY,
      timezone: DEFAULT_TIMEZONE,
      ownerName: v.ownerName,
      ownerEmail: v.ownerEmail,
      ownerPassword: v.ownerPassword,
      planId: v.planId,
      billingPeriod: v.billingPeriod,
      intent: v.intent,
    })

    return {
      ok: true,
      loginUrl: publicTenantUrl(result.slug, '/login'),
      checkoutUrl: result.checkoutUrl,
      planWarning: result.planError,
    }
  } catch (e) {
    if (e instanceof SignupError) return { error: e.message, field: e.field ?? null }
    console.error('[signup] failed:', e)
    return { error: 'Could not create your workspace. Please try again.' }
  }
}
